runtime: nodejs20
env: standard
env_variables:
  REACT_APP_API_KEY: AIzaSyBI37OFPHWswmAhKKLY1IUk-ZYerGh71j4
  REACT_APP_ADMIN_DOMAIN: physiotherapy-eb4bb.firebaseapp.com
  REACT_APP_PRODUCT_ID: physiotherapy-eb4bb
  REACT_APP_STORAGE_BUCKET: physiotherapy-eb4bb.appspot.com
  REACT_APP_MESSAGING_SENDER_ID: 337785625667
  REACT_APP_APP_ID: 1:337785625667:web:cc2807e7b129b30f2488f6
  REACT_APP_MEASUREMENT_ID: G-2DD6LR514D
  REACT_APP_GOOGLE_ANALYTICS_MEASUREMENT_ID: G-3GRXXMSKR3
  REACT_APP_GOOGLE_ANALYTICS_TRACKING_ID: UA-400757671
handlers:
  - url: /(.*\..+)$
    static_files: build/\1
    upload: build/(.*\..+)$
  - url: /.*
    static_files: build/index.html
    upload: build/index.html
